"""add create_at to integrator

Revision ID: 821872346a7a
Revises: 6c502555b854
Create Date: 2024-07-31 11:52:18.857426

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '821872346a7a'
down_revision = '6c502555b854'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integrator', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('integrator', 'created_at')
    # ### end Alembic commands ###
