{{- with .Values.job }}
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    {{- include "avialine-passenger.labels" $ | nindent 4 }}
    k8s-app: {{ .name }}
  name: {{ .name }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 100
  template:
    metadata:
      labels:
        {{- include "avialine-passenger.labels" $ | nindent 8 }}
        k8s-app: {{ .name }}
    spec:
      restartPolicy: Never
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #         - matchExpressions:
      #             - key: doks.digitalocean.com/node-pool
      #               operator: In
      #               values:
      #                 - {{ $.Values.affinity }}
      # tolerations:
      #   - key: doks.digitalocean.com/node-pool
      #     value: {{ $.Values.tolerations }}
      #     operator: Equal
      containers:
        - name: {{ .name }}
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
          {{- with $.Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $.Values.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $.Values.job.command }}
          command: {{- toYaml . | nindent 12 }}
          {{- end }}
          args: [ {{ .arg_command | quote }} ]
          imagePullPolicy: {{ $.Values.image.pullPolicy }}

---
{{- end }}

